import Register from "@/components/Auth/register";
import CopyRight from "@/components/CopyRight";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import NavBar from "@/components/Navbar";
import { getDictionary } from "../dictionaries";
export const metadata = {
    title: "Lws kart Register Page",
    description: "Generated by create next app",
};

export default async function RegisterPage({ params: { lang } }) {
    const dictionary = await getDictionary(lang);
    return (

        <>
            <Header lang={lang} />
            <NavBar lang={lang} />
            <main>

                <>
                    {/* register */}
                    <div className="contain py-16">
                        <Register dictionary={dictionary} />
                    </div>
                    {/* register */}
                </>


            </main>

            <Footer lang={lang} />
            <CopyRight lang={lang} />
        </>

    );
}
