import AddBanner from "@/components/AddBanner";
import Banner from "@/components/Banner";
import CopyRight from "@/components/CopyRight";
import Features from "@/components/Features";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import NavBar from "@/components/Navbar";
import ProductSection from "@/components/Products";
import ShopByCategories from "@/components/ShopByCategory";
import { findCategory, findTopNewArrivalProduct, findTrendingProducts } from "@/database/queries";
import { getDictionary } from "./dictionaries";

export const metadata = {
  title: "LWSKART Ecommerce - Home Page",
  description: "Generated by create next app",
};



export default async function HomePage({ params: { lang }, searchParams: { search }, }) {
  const categories = await findCategory();
  const topNewArrivalProducts = await findTopNewArrivalProduct();
  const trendingProducts = await findTrendingProducts();
  const dictionary = await getDictionary(lang);

  return (

    <>
      <Header lang={lang} search={search} />
      <NavBar lang={lang} />
      <main>
        <Banner lang={lang} />
        <Features lang={lang} />
        <ShopByCategories categories={categories} lang={lang} />
        <ProductSection SectionHeading={`${dictionary.Top_New_Arrival}`} products={topNewArrivalProducts} lang={lang} />
        <AddBanner />
        <ProductSection SectionHeading={`${dictionary.Trending_Products}`} products={trendingProducts} lang={lang} />
      </main>

      <Footer lang={lang} />
      <CopyRight lang={lang} />
    </>

  );
}
